export default {
    'WuPTx6P0p3B': 'Administrativna zanimanja',
    'u9Eo4UIWze8': 'Arhitektura',
    '5K6PGCXjW4b': 'Bankarstvo',
    '98l3dptZSQO': 'Briga o ljepoti: sport',
    '2Vpa4cYlA5Y': 'Dizajn i umjetnost',
    'bBz4TdcLnHd': 'Državna služba i neprofitne organizacije',
    'J6uGeydvp7V': 'Ekonomija: financije i računovodstvo',
    'wSkzPZBJY0j': 'Elektrotehnika',
    'iBzVC0XMHgV': 'Farmaceutika i biotehnologija',
    'TxlCXtgk7Q7': 'Graditeljstvo: geodezija: geologija',
    'AfZfBxCRLYf': 'Instalacije: održavanje i popravci',
    'hzp9Ns0xhuB': 'IT: telekomunikacije',
    'Zs3HsJefXpB': 'Ljudski resursi',
    '1BYs22DbOhm': 'Management',
    '3bz2qzJxCz7': 'Marketing: PR i mediji',
    'DEJEiSd8uQp': 'Obrazovanje i znanost',
    'gxuaNJIDyH5': 'Ostalo',
    'EWS2Jzy5I7Y': 'Poljoprivreda: šumarstvo: ribarstvo',
    'T8Dm1Y8ucvL': 'Pravo',
    'ZOWn6ALo6Jn': 'Prodaja (Trgovina)',
    'raeBzLGiI6w': 'Proizvodnja i zanatske usluge',
    'uNXIBz1AeZ7': 'Promet: transport: pomorstvo',
    'J5lGz4lTKiF': 'Sigurnost i zaštita',
    'PtbEOIMAIOI': 'Skladištenje i logistika',
    'veQBNlp9vah': 'Skrb (o djeci: starijima...)',
    'P1ng2AtJfuY': 'Strojarstvo i brodogradnja',
    '2obsaB2aBNU': 'Turizam i ugostiteljstv',
    '1hkG7gYIG1a': 'Zdravstvo: socijalni rad'
}